### ISSUE TITLE
I wonder whether you can retrieve "title call" of all idols.

### ISSUE THREAD

**Issue by acelaten** [summertriangle-dev/sparklebox#1]
Since they changed back to earlier versions, players can listen idols shouting "Idolmaster Cinderella Girls Starlight Stage". I wonder whether you can retrieve them and upload on the site.

**Comment by summertriangle-dev** [comment]
This will require some investigation...

**Comment by acelaten** [comment]
Thanks for your consideration.

**Comment by summertriangle-dev** [comment]
Fixed in d9c6c9f283ad9415abc0aacc939f97d72760e6a2

You can listen to them from any `/char` page.
