### ISSUE TITLE
Function Enhancement

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#10]
There are many users requires the function. 
Though I wanted to try to implement this, but I'll be busy next few weeks. If you can help to work it out I would be glad.

**Comment by summertriangle-dev** [comment]
Working on availability first

**Comment by CaiMiao** [comment]
Another function request from users is marking event cards and limited cards on thier card_partial. I really can't handle this case? Since I'm busy from now on.

**Comment by summertriangle-dev** [comment]
Half done. I'm figuring out how to do the gacha stuff currently.

**Comment by summertriangle-dev** [comment]
It's now in master, but you might not want to merge right now because presence data isn't auto-updated yet.

**Comment by CaiMiao** [comment]
Can you add target="_blank" for buttons (view sprites etc) in card_partial? They don't want to cover current page.

**Comment by summertriangle-dev** [comment]
Added.

**Comment by CaiMiao** [comment]
About the tl system. If you input nothing even a barrack then click submit, the original Japanese string would be submitted and replace current translated string. Can you make void string submitting disabled? Because this is likely to be condiser as unconsciously destuction.

**Comment by summertriangle-dev** [comment]
Done in bc7059af3a97282ee06cc0d68ea3f07c9d7e8555

**Comment by CaiMiao** [comment]
Thanks. No issue for now. If any I would reopen it.

**Comment by CaiMiao** [comment]
There're needs of the function of viewing SSR signature. Is there a static path for this?

**Comment by summertriangle-dev** [comment]
We'll need a new download rule in starlight_sync to have signatures on hoshimoriuta.

**Comment by summertriangle-dev** [comment]
https://hoshimoriuta.kirara.ca/sign/100191.png

Should be available in 15 minutes or so.
