### ISSUE TITLE
Disabling TLE caches also disables history entries

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#12]
Confirmed on my test site.

EDIT: gacha entries work. My mistake.

**Comment by summertriangle-dev** [comment]
Latest commit should fix it, but didn't test because computer's on the other side of the room

**Comment by CaiMiao** [comment]
History entries fixed. But TLE entries don't take immediate effect until you make some changes on TLs.

**Comment by summertriangle-dev** [comment]
Go to /tl_cacheall to regenerate the table.

**Comment by CaiMiao** [comment]
Got it. It is related to the method how it works. Thank you.
