### ISSUE TITLE
Missing voiced lines (?)

### ISSUE THREAD

**Issue by starjet** [summertriangle-dev/sparklebox#14]
Not exactly an issue per say, but any plans to add the missing voiced lines that don't have text to go with them?

For example

https://dl.dropboxusercontent.com/u/107422505/Live_Start1_00029_voice_200122_6_01.wav.mp3
https://dl.dropboxusercontent.com/u/107422505/Live_Start2_00030_voice_200122_6_02.wav.mp3

when starting lives with this card: https://starlight.kirara.ca/char/194#c_200021_head

(There are several of these per card, not just these two. From what I can see, Live_Start1, Live_Start2, Live_Skill1, Live_Skill2, Live_Skill3, Live_Clear1, Live_Clear2 are all live-related and don't have text entries in card_comments. There are also CaravanDrop1, CaravanDrop2, but naturally, only the few voiced Caravan cards have these.)

Some of the best lines among those specific to cards are among these live-related lines, so it would be nice to have them here if possible.

**Comment by CaiMiao** [comment]
Then he will need new dl rules in starlight_sync. You can just prepare for his release by adding new conditions in _init_.py and complete va_table_partial.html.

**Comment by starjet** [comment]
There should be no need of new dl rules, as these lines are also in v/card_*.acb along with the card specific lines that are already in use.
The problem is that these lines are not in the master db (possibly due to lack of any text) and thus needs to be directly accessed either by use_type and index, like how title call seems to be prepared. (To be implemented later?)
The lines I'm referring are use_type 6, from index 1 to 7.
I could try adding these to va_table_partial myself, but I don't have a proper dev environment to test it, and I don't want to make pull requests for something I haven't tested myself.

**Comment by summertriangle-dev** [comment]
Title calls are currently a hack. I'll have to figure out the proper description for each index before adding these lines.

**Comment by starjet** [comment]
I'm not exactly sure what you mean by description, but they are defined in Stage.SoundDefine._cardVoiceDataList as
			{
				SoundDefine.eCardVoiceCueId.Live_Start1,
				new SoundDefine.VoiceData(6, 1)
			},
			{
				SoundDefine.eCardVoiceCueId.Live_Start2,
				new SoundDefine.VoiceData(6, 2)
			},
			{
				SoundDefine.eCardVoiceCueId.Live_Skill1,
				new SoundDefine.VoiceData(6, 3)
			},
			{
				SoundDefine.eCardVoiceCueId.Live_Skill2,
				new SoundDefine.VoiceData(6, 4)
			},
			{
				SoundDefine.eCardVoiceCueId.Live_Skill3,
				new SoundDefine.VoiceData(6, 5)
			},
			{
				SoundDefine.eCardVoiceCueId.Live_Clear1,
				new SoundDefine.VoiceData(6, 6)
			},
			{
				SoundDefine.eCardVoiceCueId.Live_Clear2,
				new SoundDefine.VoiceData(6, 7)
			}
However, as I mentioned earlier, there are no listings for these in master.mdb, so the current method of iterating over use_type values from the db probably won't do.

**Comment by summertriangle-dev** [comment]
That's what I was looking for. I'll push in a few.

Thanks again.

**Comment by summertriangle-dev** [comment]
3966d4a

**Comment by starjet** [comment]
Nice. Thanks.

Now if you'd eventually add the lines from v/chara_*.acb too, this will pretty much be a comprehensive collection of voices.
