### ISSUE TITLE
Skill line parsing problem in Raw data table

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#16]
For an example, in [Shimamura Uzuki's Raw data table](https://starlight.kirara.ca/card/100075/table), `chance` parsing like below:
> functools.partial(<function skill_chance at 0x7f4765116c80>, {1: probability_type_t(probability_type=1, probability_min=2500, probability_max=3750, explain='超低確率で'), 2: probability_type_t(probability_type=2, probability_min=3000, probability_max=4500, explain='低確率で'), 3: probability_type_t(probability_type=3, probability_min=3500, probability_max=5250, explain='中確率で'), 4: probability_type_t(probability_type=4, probability_min=4000, probability_max=6000, explain='高確率で'), 5: probability_type_t(probability_type=5, probability_min=4500, probability_max=6750, explain='超高確率で')}, 4), 

as well as `dur`.

I think this is a small problem though, becuz not so many people would have a chance to access this. But it would be better to fix it.

**Comment by CaiMiao** [comment]
To avoid a new issue opening, I'll report here:
This limited Gacha is showing as a common gacha in gacha availability at card_partial.

**Comment by summertriangle-dev** [comment]
1. The string values of `chance` and `dur` are a quirk of the way skill_t works (they're actually functions that take a skill level). There is a hacky way to fix it, but I don't think it's worth the complexity.
2. Bit busy, I'll try and fix that tomorrow.

Also you should make more issues, it's easier to link/respond to them when every bug (or group of related bugs) has its own.

**Comment by summertriangle-dev** [comment]
The limited availability issue is fixed in 25c5a1675f6ae17ff9db9e8034a6f1203ec22cc4. It's not as tested as I would like it to be because I needed to push before the gacha changed again, but it should work.
