### ISSUE TITLE
Layout problem on main page / card partial

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#21]
Scroll bars look weird.

![qq 20160726030918](https://cloud.githubusercontent.com/assets/4640483/17113696/6b50738a-52de-11e6-94ec-a1ba5bf57e42.png)

**Comment by CaiMiao** [comment]
Closing due to obsoleted.

**Comment by summertriangle-dev** [comment]
Should be fixed by 0d05b8438286431678ae8a95ac2c6577ed11ea3a

**Comment by CaiMiao** [comment]
SOLVED
