### ISSUE TITLE
Idol birthday show by JST

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#23]
That will solve what you are aware of.

**Comment by summertriangle-dev** [comment]
Do we always want birthdays in JST?

Maybe both localtime and JST?

**Comment by CaiMiao** [comment]
But mainly Producers celebrate it in JST. Both is ok but JST does have higher priority.
Maybe, when they are available only in your time/JST, clarify it.

发自我的 iPhone

**Comment by summertriangle-dev** [comment]
Implemented in babbab45431b3983f18a08b832244381079586c5.
