### ISSUE TITLE
Sort not works in unknown condition

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#24]
Clicking on table header wont do anything.

iPhone 5s, all installed browsers died.
Firefox ESR on Debian died.

**Comment by summertriangle-dev** [comment]
6d6c48fde3464294e5740419c9d05dd1fc8c90fd fixes it for me in Firefox 46 and iOS 9.0.2.

**Comment by CaiMiao** [comment]
Solved
