### ISSUE TITLE
Wrong Regex on Happening Timestamp

### ISSUE THREAD

**Issue by ReiFan49** [summertriangle-dev/sparklebox#25]
https://github.com/summertriangle-dev/sparklebox/blob/master/api_endpoints.py#L352
aren't it supposed to either `\d+` or `[0-9]+` ?

i think this is the reason that i cannot find out the timestamp besides `timestamp` at -9~9 (wait.. it does + too on char class lol)

https://starlight.kirara.ca/api/v1/happening/+ results `{"error": "invalid literal for int() with base 10: '+'"}`

**Comment by summertriangle-dev** [comment]
fixed in 8963e9c051d492d8c88df5ba12f95410e0a16e60
