### ISSUE TITLE
About providing card list of gachas in the api "/happening"

### ISSUE THREAD

**Issue by superk589** [summertriangle-dev/sparklebox#27]
By now the api "https://starlight.kirara.ca/api/v1/happening/now"
returns gachas id, start_date, end_date, rates of rarities and so on. How about also providing the card(id) list of the current gachas? 
I also tried to get the card list by myself but still being failed. I have tried to uncompress db data get from "http://storage.game.starlight-stage.jp/dl/{true_version}/manifests/iOS_AHigh_SHigh". I used an iOS LZ4 compress library, it worked well with the my local testing data, however it always returns error when doing with the game data. In sparklebox there is code like this

``` python
bio = io.BytesIO()
bio.write(buf[4:8])
bio.write(buf[16:])
data = lz4.loads(bio.getvalue())
```

Is that means the original data needs some modifying before uncompress. Could you give me some help about how to uncompress the original data?
Thank you very much!

**Comment by summertriangle-dev** [comment]
A `gacha_t` is on the to-do list...

The LZ4 files have a 16-byte header. At offset 4 is the uncompressed file size, and at offset 8 is the compressed stream size. Both are little-endian 4-byte uints.

The rest of the file after the header is what you should pass to the lz4 decompressor.

**Comment by superk589** [comment]
closed, as not really need `gacha_t`  in app right now
