### ISSUE TITLE
Get app_ver update realtime

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#32]
Parse the [App Store](https://itunes.apple.com/jp/app/aidorumasuta-shindereragaruzu/id1016318735?mt=8) to get realtime app_ver.
I've copied an script for this purpose.

**Comment by summertriangle-dev** [comment]
I tick the app version manually for safety reasons, but it seems to work fine if you set it to something really high ([the original script does this](https://github.com/marcan/deresuteme/blob/master/apiclient.py#L70)).

**Comment by CaiMiao** [comment]
I also agree we should manually update this to a real version. But it is not limited to "auto update", as you can run it by your bash script as an automatically set env var (with little edition). Anyway, it's an OPTION.
Also you can add an env var to decide the fuction is enabled or not.

**Comment by summertriangle-dev** [comment]
closing as the PR was merged
