### ISSUE TITLE
In card_t endpoint, skill_type now is localized string not raw type id

### ISSUE THREAD

**Issue by superk589** [summertriangle-dev/sparklebox#36]
As example: 
https://starlight.kirara.ca/api/v1/card_t/100077

 "skill": {
                "id": 100077,
                "skill_name": "なんかガッポリ",
                "explain": "13秒毎、高確率でかなりの間、PERFECT/GREATのスコア17%アップ",
                "skill_type": "Score Bonus",
                ...
}

Can you use skill_type raw id instead of localized skill_type or provide both of them?

**Comment by summertriangle-dev** [comment]
API 1.4 adds the `skill_type_id` field, which is the raw type value.
