### ISSUE TITLE
About name.csv on '$TRANSIENT_DATA_DIR'

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#4]
I forked and make my own l10 branch of your system, and I'm returning errors because of lack of '$TRANSIENT_DATA_DIR'/name.csv.

Aren't this automatically created? I even don't know the correct structure of the file. Please give some suggestion, and is possible improve automatic generating the file?

Thank you.

**Comment by CaiMiao** [comment]
Ok I found it same with overwrite.csv...
Then could you make a auto update for this?
or maybe im failed with the dictionary?

Ok, here i meet 3 new problems.
First, the historical version info is missing, because I'm a new site to host this. But is there a way to fill them up?
Second, The appeal points varies by card level doesn't work. My test site is here: https://sldb-cai-miao.c9users.io , and source code is on my fork. I don't know where problem occurs due to my lack of knowledge of any coding related thing. If you could help sort out problems I would be glad.
Third, some servers don't support locale settings on your #2 of app.py, are there any fallback option?

Ty.

**Comment by summertriangle-dev** [comment]
Yes, names.csv is automatically generated, but only when the server updates itself (e.g. it won't run if the mdb already exists on startup). 

Can you can run it manually (like `python3 toolchain/name_finder.py [path to enamdictu] [path to xxx.mdb] [path to names.csv]`) and see if it produces errors?

> I even don't know the correct structure of the file.

The structure is exactly the same as _data/private/overrides.csv.

> First, the historical version info is missing, because I'm a new site to host this. But is there a way to fill them up?

Here's a mysqldump of my history entries.
https://gist.github.com/summertriangle-dev/af49588ad1b0c785e6c2c29bf1b974ee

> Second, The appeal points varies by card level doesn't work.

Worked for me when I visited your site. Good job on fixing it!

> Third, some servers don't support locale settings on your #2 of app.py, are there any fallback option?

You can set it to any locale with UTF-8. If your server doesn't have any UTF-8 locales, you're probably going to run into encoding errors when loading pages.

**Comment by CaiMiao** [comment]
Ahh, at last... the test workspace doesn't allow reading files over 8MB. Thank you for your nice coaching!
Here's another question I'm going to ask: How can I expand another convention line which can be reconized by the search module? Thank you. I'm going to make the search works both romanized kana (the original "conventional") and Chinese translation (new line).

**Comment by summertriangle-dev** [comment]
To add additional words to search:

Add more keys to the names dict here https://github.com/summertriangle-dev/sparklebox/blob/master/endpoints.py#L91 .
The format of the dict is `{ search word: [phrase that appears in the result list, chara_id] }`, e.g. `{"sakurai momoka": ["Sakurai Momoka", 115]`

If I wanted to make it so you can search a character's name backwards, I'd add this:
```python
for chara_id, name_t in starlight.data.names.items():
    names[ str( reversed( name_t.conventional ) ) ] = [name_t.conventional, chara_id]
```

Since you want to add a Chinese name for every character, you have to do two things after extending names.csv:

- Add the new attribute here to make it available to templates/API: https://github.com/summertriangle-dev/sparklebox/blob/master/starlight/__init__.py#L209 . Then you can use it anywhere ".conventional" works.
- Fix name_finder to write the new column. Add the column name to the end of the tuple in https://github.com/summertriangle-dev/sparklebox/blob/master/toolchain/name_finder.py#L180, and add the column's value at the end of this tuple: https://github.com/summertriangle-dev/sparklebox/blob/master/toolchain/name_finder.py#L209

To import the dump, just execute it in the mysql shell.

`$ mysql -u [root] -p [database name] < ss_history.sql`

**Comment by CaiMiao** [comment]
Thank you a lot!
I just found mysql on my workspace is never enabled until just know.
How I could adapt to the history db? Shall I need to reconfigure the service?

**Comment by CaiMiao** [comment]
Problem, I used sqlite phrase to import, like:
```
INSERT INTO `ss_history` (`id`, `time`, `payload`) VALUES
(1, 892364400, '{"n": [100003, 100007, 100009, 100013, 100015, 100065, 100067, 100069, 100071, 100087, 100099, 200005, 200007, 200009, 200011, 200013, 200015, 200017, 200019, 200067, 200069, 200085, 200091, 300003, 300007, 300009, 300011, 300013, 300015, 300017, 300021, 300069, 300071, 300073, 300089], "r": [100001, 100019, 100021, 100023, 100025, 100027, 100037, 100073, 100079, 100081, 100089, 200001, 200021, 200023, 200025, 200027, 200037, 200039, 200075, 200077, 200083, 300001, 300027, 300029, 300031, 300033, 300035, 300075, 300081, 300083, 300093], "sr": [100043, 100049, 100055, 100057, 100063, 100083, 100085, 200051, 200055, 200059, 200061, 200065, 200079, 200081, 200089, 300051, 300053, 300055, 300057, 300061, 300065, 300085, 300087], "ssr": [100075, 100077, 100091, 100097, 200071, 200073, 300077, 300079, 300095], "event": [100093, 100095, 200109, 300091]}')```

But server returns 500. Here's the log.

`ERROR:tornado.application:Uncaught exception GET / (218.13.32.105)
HTTPServerRequest(protocol='https', host='sldb-cai-miao.c9users.io', method='GET', uri='/', version='HTTP/1.1', remote_ip='218.13.32.105', headers={'X-Forwarded-For': '218.13.32.105', 'If-None-Match': '"535dcc16f5f2ecb40fff6b25aa2efc1f494098cd"', 'X-Region': 'ae', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36 TheWorld 7', 'Accept-Encoding': 'gzip, deflate, sdch', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-Port': '443', 'Cache-Control': 'max-age=0', 'Host': 'sldb-cai-miao.c9users.io', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'X-Forwarded-Proto': 'https', 'Accept-Language': 'zh-CN,zh;q=0.8'})
Traceback (most recent call last):
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/ubuntu/workspace/endpoints.py", line 76, in get
    for h in [x.asdict() for x in recent_history]:
  File "/home/ubuntu/workspace/endpoints.py", line 76, in <listcomp>
    for h in [x.asdict() for x in recent_history]:
  File "/home/ubuntu/workspace/tl_models.py", line 146, in get_history
    gv = rows.all()
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 71, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 428, in _instance
    loaded_instance, populate_existing, populators)
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 486, in _populate_full
    dict_[key] = getter(row)
  File "/home/ubuntu/workspace/.env/lib/python3.4/site-packages/sqlalchemy/sql/sqltypes.py", line 862, in process
    value = bytes(value)
TypeError: string argument without an encoding
ERROR:tornado.access:500 GET / (218.13.32.105) 191.91ms`

**Comment by summertriangle-dev** [comment]
Oh, I didn't know you were using SQLite. This script should work (according to google, SQLite needs hex literals when inserting BLOB). https://gist.github.com/summertriangle-dev/09fea6b539b3776407d76736f070ec3b

**Comment by CaiMiao** [comment]
No, though no 500s, but historical card addition won't show. Blank.

**Comment by summertriangle-dev** [comment]
Cherry-pick 5633cc3032d65c62be60a005e3706559c24e92d1 and they will come back.

**Comment by CaiMiao** [comment]
Solved! Now I just left a configuration of auto-updating.
My friend helped me to fetch secrets to configure it, but we have no clues about AES-KEY. Everything we tried ends up in the result res_ver=-1.
Any tips?

**Comment by summertriangle-dev** [comment]
VC_AES_KEY and VC_SID_SALT are found by disassembling the game DLLs. I can't really help further on that, but if you get really stuck... send me an email.

**Comment by CaiMiao** [comment]
Just wonder why version check returns -1?

**Comment by hyspace** [comment]
I got UDID as 8-4-4-4-12 format, is that right?

**Comment by summertriangle-dev** [comment]
I'm not sure why it would return -1 as a res ver, usually it doesn't return one at all if you got the parameters wrong.

And yes, the UDID looks like a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).

**Comment by CaiMiao** [comment]
I implemented preparation of adding new search string.

I'm not so clear how to add new dict into endpoints.py, as I can't realize the code exactly.
In addition, how should I do to force the search suggestion result to show 'kanji' value in spite of input condition (chara_ids, kanas, conventions, translated strings) ?

**Comment by summertriangle-dev** [comment]
You don't need to create a new dict, just add to the names dict that's there. What have you written so far?

To display .kanji instead of .conventional, replace

```python
names = {value.conventional.lower(): [value.conventional, key] for key, value in starlight.data.names.items()}
names.update({str(key): [value.conventional, key] for key, value in starlight.data.names.items()})
```

with 
```python
names = {value.conventional.lower(): [value.kanji, key] for key, value in starlight.data.names.items()}
names.update({str(key): [value.kanji, key] for key, value in starlight.data.names.items()})
```

in SuggestNames.

**Comment by CaiMiao** [comment]
Thank you!
I worked out this on my own, 
and I implemented kanji, kana and translated string keyword match on the search box.

Thank you a lot for coaching me. The site would avaliable soon.


发自我的 iPhone

**Comment by summertriangle-dev** [comment]
You're welcome!
