### ISSUE TITLE
Yuu Ohta page has wrong name

### ISSUE THREAD

**Issue by Robinxon** [summertriangle-dev/sparklebox#40]
Name and surname on her page are wrong so you can't search for her. Also links to Im@s Wiki and CGdex forwards to nowhere.

Link to her page: https://starlight.kirara.ca/char/120

**Comment by KanzakiRanko1** [comment]
I sent a PR, but I just reviewed it and noticed that the naming standard in Sparklebox isn't exactly the same as the ones in project-imas. Not sure if it's gonna get accepted tbh (For example, Yui suffers from the same issue: https://starlight.kirara.ca/char/246)

**Comment by summertriangle-dev** [comment]
Ideally we would use the same names that project-imas uses, but the automatic name translator has different romanization rules which makes them come out differently in some cases. I remember trying to fix this a couple years ago, but I gave up (I don't remember why anymore). Eventually I might take another crack at it when time allows.
