### ISSUE TITLE
Idol icons are mismatched

### ISSUE THREAD

**Issue by graphicjazz** [summertriangle-dev/sparklebox#41]
When viewing the gacha list the icons for a lot of the idols do not match up with the names.
<a href="https://imgur.com/a/pcXuU"> https://imgur.com/a/pcXuU
Also when viewing the idol's page the same mismatched icon will show up.
<a href="https://imgur.com/a/oIoZR"> https://imgur.com/a/oIoZR

**Comment by summertriangle-dev** [comment]
Things should be back to normal by now.
