### ISSUE TITLE
Official dropped gasha rates support of master.db

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#44]
![20171029165451](https://user-images.githubusercontent.com/4640483/32142095-4fcbde3a-bccb-11e7-9ae1-1afc28951c77.jpg)

They are now obtained through APIs.

**Comment by summertriangle-dev** [comment]
Thanks for the heads up, support for this has been added.

**Comment by superk589** [comment]
Any plan of a "gacha_t" endpoint?
Including ssr/sr/r ratio and rate of each card.

**Comment by superk589** [comment]
not really need this endpoint any more, @CaiMiao please close this issue.
