### ISSUE TITLE
New skills need to define

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#46]
http://game.starlight-stage.jp/information/detail/1239/1/10/2

Thank you in advance !

**Comment by CaiMiao** [comment]
merging

**Comment by CaiMiao** [comment]
in `enums.py` L68-70, "Deep xxx" should be corrected as "xxx Focus" according to official

**Comment by summertriangle-dev** [comment]
Sorry, that was a bad merge. Fixed.

**Comment by CaiMiao** [comment]
Closing issue
