### ISSUE TITLE
A new field in skill_data: value_3

### ISSUE THREAD

**Issue by superk589** [summertriangle-dev/sparklebox#47]
Could you include this value in apis?

**Comment by superk589** [comment]
Sorry, value_3 is already there. Closed

**Comment by summertriangle-dev** [comment]
Going to keep this open until I add strings/icons for the new skill.

**Comment by CaiMiao** [comment]
A suggestion: I think the "missing period" gasha histories should be removed because it's long, annoying and don't have a certain reference value.
