### ISSUE TITLE
A problem with shiki's leader skill in her cinfes ssr

### ISSUE THREAD

**Issue by hitxshii** [summertriangle-dev/sparklebox#48]
Her leader skill is one that increases fan gain by 30%, but on her page there's an error that says "I don't know how to describe this leader skill. This is a bug, please report it. (up_type: 1, type: 40)"

**Comment by summertriangle-dev** [comment]
Thanks for reporting. I fixed this in https://github.com/summertriangle-dev/sparklebox/commit/aadb95180420f28458b82d9c4507f0509dca61b7 (a very long time ago, but I left the issue open until now)
