### ISSUE TITLE
Need new skill type filter for Life Sparkle, Encore, and Tricolor Synergy

### ISSUE THREAD

**Issue by martelor** [summertriangle-dev/sparklebox#49]
![1](https://user-images.githubusercontent.com/39873594/40884380-e70a17be-673c-11e8-9074-893d967e6cd3.JPG)
![2](https://user-images.githubusercontent.com/39873594/40884381-e73a4b78-673c-11e8-9834-f3c06b688252.JPG)

**Comment by summertriangle-dev** [comment]
Thanks for reminding me. The new filters have been added in https://github.com/summertriangle-dev/sparklebox/commit/b16bd131a711424a76a61df8506742404e195631 .
