### ISSUE TITLE
Feature request: link for individual cards

### ISSUE THREAD

**Issue by graphicjazz** [summertriangle-dev/sparklebox#52]
Would it be possible to add a link on character pages for the individual cards?

For example when I go to https://starlight.kirara.ca/char/154 there could be a link somewhere on that page to bring me to https://starlight.kirara.ca/card/100343. Maybe on the card title?

If this feature already exists somewhere I apologize but I was not able to locate any links for the cards.

**Comment by summertriangle-dev** [comment]
Good idea - I've implemented this in https://github.com/summertriangle-dev/sparklebox/commit/3f44621a51cdedc243b480925a9b697ef05e31b7 .

This part of the card's name now becomes a link when you hover over it (long press on mobile):
<img width="216" alt="" src="https://user-images.githubusercontent.com/7821037/45345691-ec8b3e80-b55b-11e8-9a34-3702049e6e76.png">
