### ISSUE TITLE
OperationalError: too many SQL variables

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#57]
![image](https://user-images.githubusercontent.com/4640483/65371727-3f342600-dc99-11e9-9ed7-a11f0e2c9a52.png)

randomly get this, dont know why

**Comment by summertriangle-dev** [comment]
Looks like there are now enough cards in the game for us to run into sqlite API limits.

See if ab4bc749 fixes it. You can test by going to a page that loads >= 1000 cards (e.g. the URL in the screenshot, or /history) right after the server starts.

**Comment by CaiMiao** [comment]
it seems working fine, will reopen if bugs remain
