### ISSUE TITLE
History entries not automatically be shown on current event/gacha.

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#6]
Here's my site: http://starlight.hyspace.io

Comparing to starlight.kirara.ca, you can see current history entires are missing on my site.
Not only this case, the last Caravan event also missing until the event ends.
Does the problem have sth to do with the cache?
What should I do if I'm going to fix it. Ty.

**Comment by summertriangle-dev** [comment]
I made a mistake with history cache invalidation, fixed in aeba267. 

Restarting the app server will also fix it (because the cache is cleared) until the next history update.

**Comment by CaiMiao** [comment]
ok, thanks!
