### ISSUE TITLE
Akari's sprites aren't in the correct position

### ISSUE THREAD

**Issue by watatomo** [summertriangle-dev/sparklebox#60]
https://starlight.kirara.ca/sprite_go_ex/304

I'm assuming this is due to her ahoge?

**Comment by summertriangle-dev** [comment]
Yeah, it was the ahoge. It now extends out of the container for some expressions, but I decided to leave that in as a feature.

**Comment by watatomo** [comment]
Honestly, that's fine. It's kinda cute.
