### ISSUE TITLE
Cinderella Present's skill description doesn't make sense

### ISSUE THREAD

**Issue by nagi-desuuu** [summertriangle-dev/sparklebox#70]
![image](https://github.com/summertriangle-dev/sparklebox/assets/75596775/7610ff02-b908-43f7-bcd5-d28b6803c9ef)

> Always activated at the start of LIVE, recovers life to 200% and reduces life gauge decrease by 50% during LIVE [cannot be activated with Encore or Cinderella Magic]

**Comment by summertriangle-dev** [comment]
I've added the translation for this skill in 9d2b913.
