### ISSUE TITLE
July 26 Idol Produce event does not show Atsumi and Kiyora's newest cards as part of the availibility period

### ISSUE THREAD

**Issue by nagi-desuuu** [summertriangle-dev/sparklebox#74]
![image](https://github.com/user-attachments/assets/1639199a-672e-4b97-b323-602e4cd710ff)
The image above is supposed to be filled with entries on the new cards included in the event.

**Comment by summertriangle-dev** [comment]
Thanks for the report. This should be fixed going forward.
