### ISSUE TITLE
Shiki Ichinose's latest SSR images return a 404 error when clicked

### ISSUE THREAD

**Issue by nagi-desuuu** [summertriangle-dev/sparklebox#76]
Seems to be an extractor error on server-side, as it can't really check on the game anymore to get the assets from the game's servers to display on the site.

The malfunctioning entry in question: https://starlight.kirara.ca/card/101367

**Comment by summertriangle-dev** [comment]
It was an extractor issue, indeed. I've fixed it now, the images will load once the 404s fall out of cache.
