### ISSUE TITLE
Latest Idol Produce event shows no available cards, and returns a 404 when attempting to view cards in batch

### ISSUE THREAD

**Issue by nagi-desuuu** [summertriangle-dev/sparklebox#77]
Related: https://github.com/summertriangle-dev/sparklebox/issues/76

Sparklebox knows that the event exists, but it failed to get the newly released cards that came with it.

**Comment by summertriangle-dev** [comment]
This was due to the fix from #74 not deploying as expected. I've fixed it manually for now and (again) it should work going forward.
