### ISSUE TITLE
Sort idols by stats

### ISSUE THREAD

**Issue by CaiMiao** [summertriangle-dev/sparklebox#8]
There's a request from users to add ''sort'' function to sort & find idols by stats.
I suggest to add a new table for it.

**Comment by CaiMiao** [comment]
lags

**Comment by CaiMiao** [comment]
Reopened to reuse issues created by accident.

**Comment by summertriangle-dev** [comment]
I added stats to the current tables.

Sorting will come eventually...

**Comment by summertriangle-dev** [comment]
Sorting is done.

**Comment by CaiMiao** [comment]
Thank you.
